// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIWAwnCeVzbhQ_HOCMXemwAL5BCS-IpFk',
    appId: '1:128607126061:web:3b4b758cdcdcf03c71eea4',
    messagingSenderId: '128607126061',
    projectId: 'fridgeguard-1fce9',
    authDomain: 'fridgeguard-1fce9.firebaseapp.com',
    storageBucket: 'fridgeguard-1fce9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWkm7W83g3xB9Trs2AuyDHXzUnk4ewKtI',
    appId: '1:128607126061:android:6a7d9999b18fb57871eea4',
    messagingSenderId: '128607126061',
    projectId: 'fridgeguard-1fce9',
    storageBucket: 'fridgeguard-1fce9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDehW4cMqP8SuUKx0RB0JZuvGW2uEfpEWA',
    appId: '1:128607126061:ios:c5f39df0dac8ecee71eea4',
    messagingSenderId: '128607126061',
    projectId: 'fridgeguard-1fce9',
    storageBucket: 'fridgeguard-1fce9.firebasestorage.app',
    iosBundleId: 'com.example.fridgeguard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDehW4cMqP8SuUKx0RB0JZuvGW2uEfpEWA',
    appId: '1:128607126061:ios:c5f39df0dac8ecee71eea4',
    messagingSenderId: '128607126061',
    projectId: 'fridgeguard-1fce9',
    storageBucket: 'fridgeguard-1fce9.firebasestorage.app',
    iosBundleId: 'com.example.fridgeguard',
  );
}
